// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngfwenmxbgbytzhqesas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZndlbm14YmdieXR6aHFlc2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njg0OTksImV4cCI6MjA2NTU0NDQ5OX0.l0uuVeXnBBO6tMVRg03YxWkIggY7J3BUNMCiydzCvC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);