// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmbcyubllpabbfhjmpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWJjeXVibGxwYWJiZmhqbXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc3OTIsImV4cCI6MjA2NTU2Mzc5Mn0.w6D-d1rhnzMBO8UqGUaxh6DWMmSzdeQVBxAtDreU9nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);